# Generated by Django 2.1.3 on 2018-11-22 10:39

from django.db import migrations, models
import django.db.models.deletion
import fiesta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=18)),
                ('file_name', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to=fiesta.models.upload_to)),
                ('user_id', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ['-file_name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('path', models.TextField(max_length=100)),
                ('user_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiesta.Attachment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiesta.Author')),
            ],
        ),
    ]
