# Generated by Django 2.1.3 on 2018-12-07 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0002_auto_20181204_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
