# Generated by Django 2.1.3 on 2018-12-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0003_html_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='', max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
