# Generated by Django 2.1.3 on 2018-12-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0004_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
